### ISSUE TITLE
[Question] How to handle errors?

### ISSUE THREAD

**Issue by xavdid** [heroku/heroku-apps#84]
Hey! I'm making an extension and I was wondering what proper procedure for errors was. 

My code is something like this

```javascript
// command.js
yield file.write(res, fname)

// file.write
write: (obj, fname) => {
  fname = fname || DEFAULT_FNAME
  return fs.writeFile(fname, obj_to_file_format(obj)).then(() => {
    cli.log(`Successfully wrote config to ${fname}!`)
  }).catch((err) => {
    cli.error(`Error writing to file ${fname} (${err.message})`)
    // return Promise.reject()
  })
}
```

In the case of an error, should I reject the promise that gets returned from the command itself? Or will printing the error be enough and there's nothing else that depends on the success of the command? Alternatively, should I `process.exit(1)` in `command.js`? 

Thanks!

**Comment by ransombriggs** [comment]
@Xavdidtheshadow I have some code that I want to merge into `heroku-cli-utils` that will provide a best practice for this, I will let you know once this has been done & released

**Comment by Xavdidtheshadow** [comment]
@ransombriggs awesome, thanks! I settled on logging success or throwing an error ([source](https://github.com/Xavdidtheshadow/heroku-config/blob/master/util/file.js#L50)) with a message. happy to hear an official approach when it's out though.

**Comment by ransombriggs** [comment]
@Xavdidtheshadow sorry for the delayed response, been busy with other things, but finally merged in my code.  Version `5.10.11` of `heroku-cli-util` will have an exit command that you can use.
```
require('heroku-cli-util').exit(1, "Goodbye world")
```
Will print out to stderr and exit with code 1.  The reason I bothered to add this was because if you mock it out in tests it does not actually exit, it throws an `ErrorExit` error instead.  If you have questions how to use feel free to ask, and the code is here https://github.com/heroku/heroku-cli-util/blob/master/lib/exit.js .

**Comment by xavdid** [comment]
Great! Sorry I was slow, but this is exactly what I was looking for. Thanks a bunch!
